

CREATE  TABLE LOAN_ACCOUNTS
(
ACCNO CHAR(4),
CUST_NAME VARCHAR(15),
LOAN_AMOUNT DECIMAL(10,2),
INSTALLMENT INT,
INT_RATE DECIMAL(10,2),
START_DATE DATE,
INTEREST DECIMAL(10,2)

);
DESCRIBE LOAN_ACCOUNTS;

ALTER TABLE LOAN_ACCOUNTS ADD COLUMN CATEGORY VARCHAR(15);
DESCRIBE LOAN_ACCOUNTS;
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1001,'R.K GUPTA',300000.00,36,12.00,'2009-07-19');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1002,'S.P SHARMA',500000.00,48,10.00,'2008-03-22');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1003,'K.P JAIN',300000.00,36,NULL,'2007-08-03');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1004,'M.P YADAV',800000.00,60,10.00,'2008-06-12');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1005,'S.P SINHA',200000.00,36,12.50,'2010-03-01');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1006,'P SHARMA',700000.00,60,12.50,'2008-05-06');
INSERT INTO LOAN_ACCOUNTS(ACCNO,CUST_NAME,LOAN_AMOUNT,INSTALLMENT,INT_RATE,START_DATE)VALUES(1007,'K.S DHALL',500000.00,48,NULL,'2008-05-03');

SELECT * FROM LOAN_ACCOUNTS;

2. UPDATE LOAN_ACCOUNTS SET INT_RATE = INT_RATE + 0.5 WHERE LOAN_AMOUNT >400000;
    SELECT * FROM LOAN_ACCOUNTS;
1.   UPDATE LOAN_ACCOUNTS SET INT_RATE =11.50 WHERE INT_RATE IS NULL; 
    SELECT * FROM LOAN_ACCOUNTS;
   
3. UPDATE LOAN_ACCOUNTS SET INTEREST=(LOAN_AMOUNT * INT_RATE * INSTALLMENT)/(12 *100);   
    
    SELECT * FROM LOAN_ACCOUNTS;
4. DELETE   FROM LOAN_ACCOUNTS WHERE START_DATE < '2008-01-01' ; 
     SELECT * FROM LOAN_ACCOUNTS;
5. DELETE FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE 'K%';     
     SELECT * FROM LOAN_ACCOUNTS;
6.SELECT * FROM LOAN_ACCOUNTS WHERE INSTALLMENT < 40;
7. SELECT ACCNO,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE START_DATE <'2009-04-01';     
8. SELECT INT_RATE FROM LOAN_ACCOUNTS WHERE START_DATE >'2009-04-01';    
9. SELECT ACCNO,CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE'%SHARMA';
10. SELECT LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE '%A';
11. SELECT ACCNO,CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE CUST_NAME LIKE'%A%';
12. SELECT ACCNO,CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE  NOT(CUST_NAME LIKE'%P%');
13. DESCRIBE LOAN_ACCOUNTS;
14. SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT ASC;
15. SELECT * FROM LOAN_ACCOUNTS ORDER BY START_DATE  DESC;
16  SELECT * FROM LOAN_ACCOUNTS ORDER BY LOAN_AMOUNT,START_DATE DESC;
17 SELECT  ACCNO,CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS  WHERE CUST_NAME LIKE 'K%';
18  SELECT  * FROM LOAN_ACCOUNTS  WHERE INT_RATE  IS NULL;
19 SELECT  * FROM LOAN_ACCOUNTS  WHERE INT_RATE  IS  NOT NULL;
20 SELECT DISTINCT LOAN_AMOUNT FROM LOAN_ACCOUNTS;
21 SELECT * FROM LOAN_ACCOUNTS WHERE START_DATE > '2008-12-31' AND INSTALLMENT >36 ;
22  SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT <500000 OR INT_RATE > 12;
23  SELECT * FROM LOAN_ACCOUNTS WHERE YEAR(START_DATE)='2009';
24  SELECT * FROM LOAN_ACCOUNTS WHERE LOAN_AMOUNT BETWEEN 400000 AND 500000;
25  SELECT CUST_NAME,LOAN_AMOUNT FROM LOAN_ACCOUNTS WHERE INSTALLMENT IN(26,36,48);


26.SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE, CASE WHEN INT_RATE IS NULL THEN '0' ELSE INT_RATE END FROM LOAN_ACCOUNTS;
27 SELECT CUST_NAME,LOAN_AMOUNT,INT_RATE, CASE WHEN INT_RATE IS NULL THEN 'NO INTERST' ELSE INT_RATE END FROM LOAN_ACCOUNTS;